[parity]
chain = "Sokol_home.json"
base_path = "/home/koal/poa/sokol"
keys_path = "./keys"

[network]
port = 30333
nat = "none"
reserved_peers="Sokol_bootnodes.txt"

[rpc]
port = 38545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
cors = ["all"]
hosts = ["all"]

[ipc]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "parity_accounts", "traces", "rpc", "shh", "shh_pubsub", "personal"]

[ui]
port = 38180
force = true

[websockets]
port = 38546

[account]
unlock = ["0x842eb2142c5aa1260954f07aae39ddee1640c3a7"]
password = ["./keys/passwd/home_842eb2142c5aa1260954f07aae39ddee1640c3a7.pwd"]
#password = ["/home/koal/git-repos/parity-bridge-research/erc20/tmp_passwd"]
