estimated_gas_cost_of_withdraw = 0
#max_total_home_contract_balance = "10000000000000000000"
#max_single_deposit_value = "1000000000000000000"

[home]
account = "0x842eb2142c5aa1260954f07aae39ddee1640c3a7"
ipc = "/home/koal/parity/Sokol_home/jsonrpc.ipc"
required_confirmations = 1
poll_interval = 5
request_timeout = 10

[home.contract]
bin = "contracts.opt/HomeBridge.bin"

[foreign]
account = "0xf3ee321df87781864f46f6464e764c2827fca73b"
ipc = "/opt/storage/Ropsten/jsonrpc.ipc"
required_confirmations = 1
poll_interval = 20
request_timeout = 10

[foreign.contract]
bin = "contracts.opt/ForeignBridge.bin"

[authorities]
accounts = [
	"0xf3ee321df87781864f46f6464e764c2827fca73b"
]
required_signatures = 1

[transactions]
home_deploy = { gas = 3000000, gas_price = 1000000000 }
foreign_deploy = { gas = 3000000, gas_price = 5000000000 }
deposit_relay = { gas = 300000, gas_price = 18000000000 }
withdraw_confirm = { gas = 300000, gas_price = 18000000000 }
withdraw_relay = { gas = 300000, gas_price = 1000000000 }
